# ==============================================================================
# 01_prepare_cmip6_download_manifest.R
# ==============================================================================
# Southern right whale (SRW) project
#
# PURPOSE
#   Convert the raw ESGF query generated by 00_query_cmip6_srw.R into the exact
#   download manifest used by the SRW workflow.
#
# THIS SCRIPT
#   - keeps only MIROC-ES2L and MRI-ESM2-0;
#   - keeps the final ensemble member selected for each ESM;
#   - keeps the native grid (gn);
#   - restricts experiments to the required SRW periods;
#   - creates reproducible output filenames and directories;
#   - writes one clean CSV manifest for the downloader.
#
# OUTPUT
#   01_SRW_CMIP6_download_manifest.csv
#
# NEXT SCRIPT
#   02_download_cmip6_srw.R
# ============================================================================== 

# ---- 1. Packages --------------------------------------------------------------

library(dplyr)
library(stringr)
library(lubridate)

# ---- 2. Configuration ---------------------------------------------------------

QUERY_DIR <- "/Users/jazelouled-cheikhbonan/Dropbox/2024_SouthernRightWhaleLogbooks_MRuiz/InputOutput/00input/00enviro/queryCMIP6"

# Change this path only if the external-drive location changes.
RAW_ROOT <- "/Volumes/23327-15324-35628/2024_SouthernRightWhaleLogbooks/00rawData/UsedESM"

PAST_QUERY_FILE <- file.path(QUERY_DIR, "00_query_PMIP_past1000_raw.csv")
FUTURE_QUERY_FILE <- file.path(QUERY_DIR, "00_query_CMIP_historical_SSP_raw.csv")
MANIFEST_FILE <- file.path(QUERY_DIR, "01_SRW_CMIP6_download_manifest.csv")

# Final ensemble members used in the SRW project.
FINAL_MEMBER <- c(
  "MIROC-ES2L" = "r1i1p1f2",
  "MRI-ESM2-0" = "r1i1p1f1"
)

FINAL_ESMS <- names(FINAL_MEMBER)
FINAL_EXPERIMENTS <- c("past1000", "historical", "ssp126", "ssp585")

OCEAN_VARIABLES <- c(
  "tos", "sos", "so", "mlotst", "zos", "uo", "vo",
  "tauuo", "tauvo", "wo", "thetao"
)
SEA_ICE_VARIABLES <- "siconc"
FINAL_VARIABLES <- c(OCEAN_VARIABLES, SEA_ICE_VARIABLES)

# Analysis period used by the SRW environmental reconstruction.
PERIOD_START <- as.POSIXct(c(
  past1000 = "1700-01-01 00:00:00",
  historical = "1850-01-01 00:00:00",
  ssp126 = "2015-01-01 00:00:00",
  ssp585 = "2015-01-01 00:00:00"
), tz = "UTC")

PERIOD_END <- as.POSIXct(c(
  past1000 = "1849-12-31 23:59:59",
  historical = "2014-12-31 23:59:59",
  ssp126 = "2100-12-31 23:59:59",
  ssp585 = "2100-12-31 23:59:59"
), tz = "UTC")

# ---- 3. Input checks ----------------------------------------------------------

required_files <- c(PAST_QUERY_FILE, FUTURE_QUERY_FILE)
missing_files <- required_files[!file.exists(required_files)]

if (length(missing_files) > 0) {
  stop(
    "Missing raw query file(s):\n",
    paste(missing_files, collapse = "\n"),
    "\nRun 00_query_cmip6_srw.R first."
  )
}

# ---- 4. Read and combine raw queries -----------------------------------------

query_past <- read.csv(PAST_QUERY_FILE, stringsAsFactors = FALSE)
query_future <- read.csv(FUTURE_QUERY_FILE, stringsAsFactors = FALSE)

query_all <- bind_rows(query_past, query_future)

required_columns <- c(
  "file_id", "dataset_id", "source_id", "experiment_id", "member_id",
  "grid_label", "nominal_resolution", "variable_id", "datetime_start",
  "datetime_end", "file_url"
)

missing_columns <- setdiff(required_columns, names(query_all))
if (length(missing_columns) > 0) {
  stop("Raw query is missing required column(s): ", paste(missing_columns, collapse = ", "))
}

query_all$datetime_start <- as.POSIXct(query_all$datetime_start, tz = "UTC")
query_all$datetime_end <- as.POSIXct(query_all$datetime_end, tz = "UTC")

# ---- 5. Keep the final SRW ESM/member/grid combinations ----------------------

manifest <- query_all %>%
  filter(
    source_id %in% FINAL_ESMS,
    experiment_id %in% FINAL_EXPERIMENTS,
    variable_id %in% FINAL_VARIABLES,
    grid_label == "gn"
  ) %>%
  filter(member_id == unname(FINAL_MEMBER[source_id]))

# ---- 6. Restrict files to the required temporal windows ----------------------
# A NetCDF file is retained if its time span overlaps the target experiment
# interval. This is safer than relying on the catalogue query to crop by year.

keep_time <- vapply(seq_len(nrow(manifest)), function(i) {
  experiment <- manifest$experiment_id[i]
  file_start <- manifest$datetime_start[i]
  file_end <- manifest$datetime_end[i]

  if (is.na(file_start) || is.na(file_end)) return(FALSE)

  file_start <= PERIOD_END[[experiment]] && file_end >= PERIOD_START[[experiment]]
}, logical(1))

manifest <- manifest[keep_time, , drop = FALSE]

# ---- 7. Construct local filenames and output directories ---------------------

format_cmip_date <- function(x) {
  format(as.POSIXct(x, tz = "UTC"), "%Y%m%d")
}

manifest <- manifest %>%
  mutate(
    base_file_name = str_remove(dataset_id, "\\|.*$"),
    out_file_name = paste0(
      base_file_name, ".",
      format_cmip_date(datetime_start), "_",
      format_cmip_date(datetime_end),
      ".nc"
    ),
    resolution_folder = str_remove_all(nominal_resolution, "\\s+"),
    out_full_folder = file.path(
      RAW_ROOT,
      source_id,
      experiment_id,
      resolution_folder
    ),
    out_path = file.path(out_full_folder, "raw", out_file_name)
  ) %>%
  distinct(file_id, .keep_all = TRUE) %>%
  arrange(source_id, experiment_id, variable_id, datetime_start)

# ---- 8. Sanity checks ---------------------------------------------------------

if (nrow(manifest) == 0) {
  stop("The final SRW download manifest is empty. Check the raw query and filters.")
}

# MIROC-ES2L does not provide mlotst in the selected setup. This is expected.
if (any(manifest$source_id == "MIROC-ES2L" & manifest$variable_id == "mlotst")) {
  warning("mlotst was returned for MIROC-ES2L. Check whether this is expected before downloading.")
}

summary_manifest <- manifest %>%
  count(source_id, member_id, experiment_id, variable_id, nominal_resolution, name = "n_files") %>%
  arrange(source_id, experiment_id, variable_id)

cat("\nFinal SRW download manifest summary:\n")
print(summary_manifest, n = Inf)

size_gb <- sum(manifest$file_size, na.rm = TRUE) / 1024^3
cat(sprintf("\nFiles to download: %d\n", nrow(manifest)))
cat(sprintf("Approximate total catalogue size: %.2f GB\n", size_gb))

# ---- 9. Save manifest ---------------------------------------------------------

write.csv(manifest, MANIFEST_FILE, row.names = FALSE)

cat("\nSaved download manifest:\n", MANIFEST_FILE, "\n", sep = "")
cat("\n01_prepare_cmip6_download_manifest.R finished successfully.\n")
cat("Next: run 02_download_cmip6_srw.R\n")
