# ==============================================================================
# 02_download_cmip6_srw.R
# ==============================================================================
# Southern right whale (SRW) project
#
# PURPOSE
#   Download the exact NetCDF files listed in the clean SRW CMIP6 manifest
#   generated by 01_prepare_cmip6_download_manifest.R.
#
# BEHAVIOUR
#   - never overwrites an existing non-empty NetCDF file;
#   - downloads first to a temporary .part file;
#   - retries failed downloads;
#   - writes a download log that allows interrupted runs to be resumed safely.
#
# INPUT
#   01_SRW_CMIP6_download_manifest.csv
#
# OUTPUT
#   RAW NetCDF files under:
#   <RAW_ROOT>/<ESM>/<experiment>/<resolution>/raw/
# ============================================================================== 

# ---- 1. Packages --------------------------------------------------------------

library(curl)

# ---- 2. Configuration ---------------------------------------------------------

QUERY_DIR <- "/Users/jazelouled-cheikhbonan/Dropbox/2024_SouthernRightWhaleLogbooks_MRuiz/InputOutput/00input/00enviro/queryCMIP6"

MANIFEST_FILE <- file.path(QUERY_DIR, "01_SRW_CMIP6_download_manifest.csv")
DOWNLOAD_LOG <- file.path(QUERY_DIR, "02_SRW_CMIP6_download_log.csv")

MAX_ATTEMPTS <- 3
RETRY_WAIT_SECONDS <- 10

# ---- 3. Read manifest ---------------------------------------------------------

if (!file.exists(MANIFEST_FILE)) {
  stop("Download manifest not found:\n", MANIFEST_FILE,
       "\nRun 01_prepare_cmip6_download_manifest.R first.")
}

manifest <- read.csv(MANIFEST_FILE, stringsAsFactors = FALSE)

required_columns <- c("file_url", "out_file_name", "out_path")
missing_columns <- setdiff(required_columns, names(manifest))

if (length(missing_columns) > 0) {
  stop("Manifest is missing required column(s): ", paste(missing_columns, collapse = ", "))
}

if (nrow(manifest) == 0) stop("The download manifest is empty.")

# ---- 4. Helpers ---------------------------------------------------------------

file_is_complete_enough <- function(path) {
  file.exists(path) && !is.na(file.info(path)$size) && file.info(path)$size > 0
}

download_one <- function(url, destination, max_attempts = 3) {
  dir.create(dirname(destination), recursive = TRUE, showWarnings = FALSE)

  if (file_is_complete_enough(destination)) {
    return(list(status = "already_exists", attempts = 0L, message = NA_character_))
  }

  part_file <- paste0(destination, ".part")
  if (file.exists(part_file)) file.remove(part_file)

  last_error <- NA_character_

  for (attempt in seq_len(max_attempts)) {
    cat(sprintf("    Attempt %d/%d\n", attempt, max_attempts))

    ok <- tryCatch({
      curl::curl_download(
        url = url,
        destfile = part_file,
        quiet = FALSE,
        mode = "wb"
      )
      TRUE
    }, error = function(e) {
      last_error <<- conditionMessage(e)
      FALSE
    })

    if (ok && file_is_complete_enough(part_file)) {
      if (file.exists(destination)) file.remove(destination)

      renamed <- file.rename(part_file, destination)
      if (!renamed) {
        file.copy(part_file, destination, overwrite = FALSE)
        file.remove(part_file)
      }

      if (file_is_complete_enough(destination)) {
        return(list(status = "downloaded", attempts = attempt, message = NA_character_))
      }
    }

    if (file.exists(part_file)) file.remove(part_file)

    if (attempt < max_attempts) {
      cat("    Download failed; retrying in ", RETRY_WAIT_SECONDS, " s...\n", sep = "")
      Sys.sleep(RETRY_WAIT_SECONDS)
    }
  }

  list(status = "failed", attempts = max_attempts, message = last_error)
}

# ---- 5. Download --------------------------------------------------------------

log_rows <- vector("list", nrow(manifest))

cat("\n============================================================\n")
cat("SRW CMIP6 DOWNLOAD\n")
cat("============================================================\n")
cat("Files in manifest:", nrow(manifest), "\n\n")

for (i in seq_len(nrow(manifest))) {
  destination <- manifest$out_path[i]
  url <- manifest$file_url[i]

  cat(sprintf("[%d/%d] %s\n", i, nrow(manifest), manifest$out_file_name[i]))

  result <- download_one(
    url = url,
    destination = destination,
    max_attempts = MAX_ATTEMPTS
  )

  cat("    Status:", result$status, "\n\n")

  log_rows[[i]] <- data.frame(
    timestamp = format(Sys.time(), "%Y-%m-%d %H:%M:%S"),
    source_id = if ("source_id" %in% names(manifest)) manifest$source_id[i] else NA_character_,
    experiment_id = if ("experiment_id" %in% names(manifest)) manifest$experiment_id[i] else NA_character_,
    variable_id = if ("variable_id" %in% names(manifest)) manifest$variable_id[i] else NA_character_,
    out_file_name = manifest$out_file_name[i],
    out_path = destination,
    status = result$status,
    attempts = result$attempts,
    message = result$message,
    stringsAsFactors = FALSE
  )

  # Update the log after every file so an interrupted run still leaves a record.
  write.csv(do.call(rbind, log_rows[seq_len(i)]), DOWNLOAD_LOG, row.names = FALSE)
}

# ---- 6. Final report ----------------------------------------------------------

log_df <- do.call(rbind, log_rows)

cat("\n============================================================\n")
cat("DOWNLOAD COMPLETE\n")
cat("============================================================\n")
print(table(log_df$status, useNA = "ifany"))
cat("\nDownload log:\n", DOWNLOAD_LOG, "\n", sep = "")

failed <- log_df[log_df$status == "failed", , drop = FALSE]

if (nrow(failed) > 0) {
  cat("\nWARNING:", nrow(failed), "file(s) failed to download.\n")
  cat("Re-run this script to retry them; existing files will be skipped.\n")
} else {
  cat("\nAll files in the SRW manifest are present.\n")
}
